# roles/rabbitmq/tasks/main.yml
---
- name: Run RabbitMQ installation script
  ansible.builtin.script: install_rabbitmq_bullseye.sh
  become: true
- name: Enable RabbitMQ Management Plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
- name: Ensure RabbitMQ service is running
  service:
    name: rabbitmq-server
    state: started
    enabled: true
- name: Remove guest user
  rabbitmq_user:
    user: guest
    state: absent
- name: Create vhost
  rabbitmq_vhost:
    name: "{{ rabbitmq_vhost }}"
    state: present
- name: Create user with privileges
  rabbitmq_user:
    user: "{{ rabbitmq_user }}"
    password: "{{ rabbitmq_password }}"
    vhost: "{{ rabbitmq_vhost }}"
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
- name: Create systemd override directory for RabbitMQ service limits
  ansible.builtin.file:
    path: /etc/systemd/system/rabbitmq-server.service.d
    state: directory
    mode: '0755'
  become: true
- name: Deploy systemd limits override for RabbitMQ service
  ansible.builtin.template:
    src: rabbitmq-limits.conf.j2
    dest: /etc/systemd/system/rabbitmq-server.service.d/limits.conf
    mode: '0644'
  become: true
- name: Deploy ERL_MAX_PORTS limits override for RabbitMQ service
  ansible.builtin.template:
    src: rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf
    mode: '0644'
  become: true
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
- name: Restart RabbitMQ service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
  become: true
